name: License Generator

on:
  workflow_dispatch:
    inputs:
      software_id:
        description: "Enter the software ID (e.g., /mr9D8LMiqL)"
        required: true
        default: "/mr9D8LMiqL"

jobs:
  generate_license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run License Generator
        run: |
          echo "Running license generator for software ID: ${{ github.event.inputs.software_id }}"
          python3 license.py licgenchr "${{ github.event.inputs.software_id }}" 9DBC845E9018537810FDAE62824322EEE1B12BAD81FCA28EC295FB397C61CE0B
